# Generated by Django 2.1.2 on 2019-01-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='categories',
        ),
    ]
